name: Test node application

on:
  workflow_call:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install
        run: npm ci
      - name: Check formatting and linting
        run: npm run lint-ci
      - name: Build
        run: npm run build
